In [ ]:
import pandas as pd
data=pd.read_csv("/content/Social_Network_Ads.csv")
data

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x=data.iloc[:,[2,3]].values
y=data.iloc[:,4].values


In [ ]:
print(data.columns[[2,3]])
print(data.columns[4])

Index(['Age', 'EstimatedSalary'], dtype='object')
Purchased


In [ ]:
#splitting the dataset into training and testing dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

#Feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [ ]:
#Create a decision tree classifer object

from sklearn.tree import DecisionTreeClassifier
model= DecisionTreeClassifier(criterion="entropy",max_depth=None,min_samples_split=5, min_samples_leaf=2)

model.fit(x_train,y_train)   #training the model
print(model)

y_pred_dec= model.predict(x_test)   #predict the testing model
y_pred_dec

from sklearn.metrics import confusion_matrix  #Making the confusion matrix
cm=confusion_matrix(y_test,y_pred_dec)
print(cm)

from sklearn.metrics import accuracy_score
print("Decision tree",accuracy_score(y_test,y_pred_dec))



DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)
[[66  2]
 [ 6 26]]
Decision tree 0.92


In [ ]:
#create an object of the algorithm/ model
from sklearn.linear_model import LogisticRegression
modellr=LogisticRegression(random_state=0)

modellr.fit(x_train,y_train)   #training the model
print(modellr)

y_pred_lr= modellr.predict(x_test)   #predict the testing model
y_pred_lr

from sklearn.metrics import confusion_matrix  #Making the confusion matrix
cmlr=confusion_matrix(y_test,y_pred_lr)
print(cmlr)

from sklearn.metrics import accuracy_score
print(" Logistic Regression",accuracy_score(y_test,y_pred_lr))



LogisticRegression(random_state=0)
[[65  3]
 [ 8 24]]
 Logistic Regression 0.89


In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFmodel= RandomForestClassifier(n_estimators=200, criterion='entropy',random_state=0)
RFmodel.fit(x_train,y_train)

#predicting the test set results

y_pred_rf= RFmodel.predict(x_test)

from sklearn.metrics import confusion_matrix  #Making the confusion matrix
cmrf=confusion_matrix(y_test,y_pred_rf)
print(cmrf)

from sklearn.metrics import accuracy_score
print("Random Forest",accuracy_score(y_test,y_pred_rf))

[[64  4]
 [ 4 28]]
Random Forest 0.92
